module.exports = {
  CREATE_TASK: 'CREATE_TASK',
  CREATED_TASK: 'CREATED_TASK',

  UPDATE_TASK: 'UPDATE_TASK',
  UPDATED_TASK: 'UPDATED_TASK',

  COMPLETE_TASK: 'COMPLETE_TASK',
  COMPLETED_TASK: 'COMPLETED_TASK',

  DELETE_TASK: 'DELETE_TASK',
  DELETED_TASK: 'DELETED_TASK',

  GOT_TASKS: 'GOT_TASKS',

  CREATE_LIST: 'CREATE_LIST',
  CREATED_LIST: 'CREATED_LIST',

  UPDATE_LIST: 'UPDATE_LIST',
  UPDATED_LIST: 'UPDATED_LIST',

  COMPLETE_LIST: 'COMPLETE_LIST',
  COMPLETED_LIST: 'COMPLETED_LIST',

  GOT_LISTS: 'GOT_LISTS'

  // GOT_CURRENT_HERO: 'GOT_CURRENT_HERO',
  // GOT_HEROES: 'GOT_HEROES',

  // GOT_MAP: 'GOT_MAP',
  // GOT_MAP_OBJECTS: 'GOT_MAP_OBJECTS'
};
